# Generated by Django 5.0 on 2024-09-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='news',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
