# Generated by Django 5.1.1 on 2024-09-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_delete_editstuff_delete_friendlygame_delete_gametype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_profile',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='player_profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='player_profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='player_profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='player_profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player_profile',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FutureStar_App.usergender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
