# Generated by Django 5.0 on 2024-09-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0002_rename_description_news_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_members',
            old_name='designations',
            new_name='designations_en',
        ),
        migrations.RenameField(
            model_name='team_members',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='news_date',
        ),
        migrations.AddField(
            model_name='team_members',
            name='designations_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team_members',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
